name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - sbt_version: "1.8.2"

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11 # it auto caches https://github.com/actions/setup-java#caching-packages-dependencies
      uses: actions/setup-java@v3.11.0
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'

    - name: Run tests
      run: sbt scalafmtAll scripted
