name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - sbt_version: "1.8.2"

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: SBT_VERSION="${{ matrix.sbt_version }}" make test
